GoogleCloudPlatform/ruby-docs-samples

- lib/storage/list_buckets.rb
- spec/storage/list_buckets_spec.rb
Standardize directories on the api_name.
> 'cloud_storage' -> 'storage'

- storage/list_buckets.rb
- adds 'all' region for docs
- makes example classes consistent with bigquery classes
> updates for storage example

- .gitignore
- .travis.yml
- appengine/hello_world/Gemfile.lock
- appengine/hello_world/Rakefile
- appengine/hello_world/spec/hello_world_spec.rb
- spec/e2e.rb
- spec/e2e_cleanup.rb
> adds appengine hello world e2e tests

- appengine/endpoints/Gemfile
- appengine/endpoints/Gemfile.lock
- appengine/endpoints/README.md
- appengine/endpoints/app.rb
- appengine/endpoints/app.yaml
- appengine/endpoints/clients/echo_client.rb
- appengine/endpoints/clients/google_id_token_client.rb
- appengine/endpoints/clients/google_jwt_client.rb
- appengine/endpoints/index.html
- appengine/endpoints/spec/endpoint_sample_spec.rb
- appengine/endpoints/swagger.yaml
> Endpoints sample for App Engine flexible environment

- appengine/cloudsql/README.md
- appengine/cloudsql/app.rb
- appengine/cloudsql/app.yaml
- appengine/cloudsql/create_tables.rb
- appengine/cloudsql/spec/cloudsql_spec.rb
- Use socket instead of host
- Update README
> Update Cloud SQL sample to use Cloud SQL second generation

- pubsub/sample.rb
- pubsub/spec/sample_spec.rb
- Add snippets
- Align variable assignments in snippets
> Add Pub/Sub snippets for deleting topics and subscriptions

- circle.yml
- spec/run-all.sh
*Note: This version of circle.yml only works on the circleci branch for reviewing purposes.
Added circle.yml which tests all non AppEngine tests.
It tests for Ruby versions 2.3.1 and 2.2.5.
Last Run with CircleCI
https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/110
> Add CircleCI to Master!

- language/spec/language_samples_spec.rb
I changed the negative text, because the polarity was coming back positive for "I am angry". (Machine Learning). 
@remi
> Fix language bug

- spec/run-all.sh
> Fix endpoints tests.

- endpoints/getting-started/README.md
These updates are to make the Endpoints README consistent with the
READMEs for the other languages.
> Updates the Endpoints README.

- endpoints/getting-started/Dockerfile.custom
- endpoints/getting-started/container-engine.yaml
Need to swap ports to line up with samples in other languages.
> Swap ports for Endpoints docker image.

- appengine/analytics/spec/google_analytics_spec.rb
- appengine/datastore/spec/datastore_spec.rb
- appengine/hello_world/spec/hello_world_spec.rb
- appengine/mailgun/spec/mailgun_spec.rb
- appengine/memcache/spec/memcache_spec.rb
- appengine/metadata_server/spec/metadata_server_spec.rb
- appengine/pubsub/spec/pubsub_spec.rb
- appengine/sendgrid/spec/sendgrid_spec.rb
- appengine/static_files/rails/spec/features/static_file_serving_spec.rb
- appengine/static_files/sinatra/spec/static_file_serving_spec.rb
- appengine/storage/spec/storage_spec.rb
- appengine/twilio/spec/twilio_spec.rb
- spec/run-all.sh
`E2E=true` is required for the e2e tests to run
> adds e2e tests to run-all.sh

- translate/spec/translate_samples_spec.rb
- translate/translate_samples.rb
https://cloud.google.com/translate/docs/premium#sample_code
> Add sample: Translate text with premium model

- language/README.md
- language/language_samples.rb
- language/spec/language_samples_spec.rb
Adjusted language_samples to demo two key features
1 - Entities sample shows off proper noun detection.
2 - Sentiment sample shows off sentence level sentiment.
Fixed Tests. Addressed CR fdbk from remi.
> Natural Language: Add proper noun detection and sentence sentiment samples

- language/README.md
- speech/README.md
- translate/README.md
- vision/README.md
This PR will update/cleanup the ML API sample READMEs.
> Cleanup Machine Learning READMEs

- appengine/rails-cloudsql-mysql/Gemfile
Removing a space in a region tag of the Gemfile. This is a XS change to remove this space.
> [App Engine sample] Remove space from Rails CloudSQL sample.

- speech/quickstart.rb
- speech/speech_samples.rb
There was some confusion where folks thought the API was only transcribing the first portion of the audio, when in fact it was because they were only using the first result. I'm updating the samples to try to reduce that confusion. See b/64934785
> Print out all the speech results

- storage/README.md
- storage/buckets.rb
- storage/spec/buckets_spec.rb
This PR is to support the following samples:
* get_bucket_labels
* add_bucket_label
* remove_bucket_label
* create_bucket_class_location (create bucket with location and storage_class).
Also, fixed a few issues that made it through in the requester pays PR.
> [Storage] Add samples for labels and create bucket with location and storage_class

- storage/files.rb
- storage/spec/files_spec.rb
This PR is to add sample for setting fixed key and custom metadata for a Cloud Storage file.
> [Storage] Canonical Set Metadata sample

- spanner/README.md
- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
This PR is to add a Read Stale Data sample for Ruby.
@remi PTAL, if you're unable to review by this Friday, I'll review it as you recommended.
> [Spanner] Add Read Stale Data sample

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
At the request of the spanner team.
> Bump spanner stale read from 10 to 15 seconds.

- language/language_samples.rb
Update comment in classify text using GCS URI.
> [Storage] Update storage_path comment to use gs:// URI

- CODE_OF_CONDUCT.md
Add code of conduct to repo. Based on #74.
> [Documentation] Add Code of Conduct

- endpoints/getting-started/app.yaml
I want to use a docwidget to display app.yaml in the docs.
> Update comments and add region tags

- endpoints/getting-started/deployment.yaml
Change SERVICE_VERSION to SERVICE_CONFIG_ID to be consistent with the Getting Started with Endpoints on Kubernetes Engine tutorial and the deployment.yaml file in the java-docs-samples, python-docs-samples, and golang samples.
> Change placeholder value

- storage/Gemfile.lock
- storage/README.md
- storage/files.rb
- storage/spec/files_spec.rb
Public Data access sample for https://cloud.google.com/storage/docs/access-public-data.
> [Storage] Add public data access sample

- .kokoro/docker/Dockerfile
This is a PR to begin adding Kokoro into ruby-docs-samples.
> [Kokoro] Add kokoro Dockerfile for Ruby

- .kokoro/common.cfg
- .kokoro/system_tests.cfg
- .kokoro/system_tests.sh
- .kokoro/trampoline.sh
Adding base configuration files for Kokoro.
> [Kokoro] Adding Kokoro configuration files

- iot/iot.rb
- iot/spec/iot_spec.rb
Missed one method in initial commit!
> Adds list states

- .kokoro/presubmit.cfg
> [Kokoro] Test presubmit

- bigquery/spec/bigquery_sample_spec.rb
- bigquery/tables.rb
Adds samples to be used on [this page](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json)
Code for canonical python sample [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8a1dc598f648d852dc45da02d1cae194e044d622/docs/bigquery/snippets.py#L503)
> BigQuery: Adds samples for JSON load jobs from GCS

- cdn/Gemfile
- cdn/Gemfile.lock
- cdn/README.md
- cdn/sign_url.rb
- cdn/spec/resources/key.txt
- cdn/spec/sign_url_spec.rb
This PR add a sample for signing Cloud CDN URLs in Ruby. It's a WIP.
> Add base sample for signing urls

- spanner/spanner_samples.rb
Related:
* ~~googleapis/nodejs-spanner#136~~ merged
* ~~GoogleCloudPlatform/python-docs-samples#1376~~ merged
* ~~GoogleCloudPlatform/java-docs-samples#1045~~ merged
* GoogleCloudPlatform/dotnet-docs-samples#454
* GoogleCloudPlatform/php-docs-samples#562
* GoogleCloudPlatform/golang-samples#403
> Clean up Spanner region tags.

- .kokoro/system_tests.sh
- spec/kokoro-run-all.sh
- storage/Gemfile.lock
This is a PR to use all system tests during a Kokoro build.
> [Kokoro] Add Auth Tests

- spec/kokoro-run-all.sh
Add CDN test into Kokoro.
#251
> [Kokoro] Add CDN test

- auth/auth.rb
Related:
* GoogleCloudPlatform/python-docs-samples#1417
* GoogleCloudPlatform/google-cloud-java#3066
> Clean up Auth region tags.

- spec/kokoro-run-all.sh
> [Kokoro] Add Translate API tests

- spec/kokoro-run-all.sh
> [Kokoro] Add Speech

- language/spec/language_samples_spec.rb
- spec/kokoro-run-all.sh
> [Kokoro] Add Language tests

- kms/Gemfile
- kms/Gemfile.lock
- kms/spec/kms_spec.rb
- kms/spec/quickstart_spec.rb
- spec/kokoro-run-all.sh
> [Kokoro] Add KMS testing

- spec/kokoro-run-all.sh
> [Kokoro] Add Video tests

- pubsub/Gemfile.lock
- spec/kokoro-run-all.sh
> [Kokoro] Add PubSub tests

- spanner/Gemfile.lock
- spanner/README.md
- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
Adding Spanner Commit Timestamp samples
Waiting for tests to pass before merging.
> [Spanner] Add spanner commit timestamp samples

- bigquery/spec/bigquery_sample_spec.rb
- bigquery/tables.rb
Resolves https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/246
> BigQuery: Adds sample for creating a table with a schema

- bigquery/datasets.rb
- bigquery/tables.rb
Updating to standard region tags will allow for better sample tracking
> BigQuery: Updates region tags to standard and deletes unused region tags

- stackdriver/Gemfile
- stackdriver/logging.ru
- stackdriver/rails_configuration.rb
- stackdriver/shared_config.ru
**Do not merge** until we've updated all the appropriate region tags
asking @beccca to review, since @frankyn is OOO
> Logging: update region tags

- storage/Gemfile.lock
- storage/README.md
- storage/buckets.rb
- storage/files.rb
- storage/spec/buckets_spec.rb
- storage/spec/files_spec.rb
> [Storage] Fix sample bugs.

- spanner/Gemfile.lock
- spanner/README.md
- spanner/quickstart.rb
- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
> Adding Spanner STRUCT param samples

- dialogflow/context_management.rb
- dialogflow/detect_intent_audio.rb
- dialogflow/detect_intent_stream.rb
- dialogflow/detect_intent_texts.rb
- dialogflow/spec/context_management_spec.rb
- dialogflow/spec/entity_management_spec.rb
- dialogflow/spec/entity_type_management_spec.rb
- dialogflow/spec/intent_management_spec.rb
- dialogflow/spec/session_entity_type_management_spec.rb
- dialogflow/spec/spec_helper.rb
- spec/kokoro-run-all.sh
> kokoro: de-flake some dialogflow tests and enable logging tests

- spec/kokoro-run-all.sh
> kokoro: always exit 0 when setting CHANGED_DIRS

- spec/kokoro-run-all.sh
- storage/spec/acls_spec.rb
- storage/spec/buckets_spec.rb
- storage/spec/files_spec.rb
- storage/spec/helpers.rb
- storage/spec/iam_spec.rb
- storage/spec/spec_helpers.rb
> kokoro: enable storage tests

- .kokoro/configure_gcloud.sh
- .kokoro/system_tests.sh
- appengine/README.md
- appengine/analytics/Gemfile.lock
- spec/e2e.rb
- spec/kokoro-run-all.sh
> testing: enable first E2E appengine tests

- spec/kokoro-run-all.sh
> kokoro: test specific appengine directories

- spec/kokoro-run-all.sh
> kokoro: run appengine/endpoints tests

- dialogflow/spec/entity_management_spec.rb
- dialogflow/spec/spec_helper.rb
Fixes #313 (will reopen if there are additional problems).
> dialogflow: add retry logic to all tests

- appengine/storage/Gemfile
- appengine/storage/Gemfile.lock
- appengine/storage/spec/storage_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/storage tests

- appengine/analytics/Gemfile
- appengine/analytics/Gemfile.lock
- appengine/analytics/spec/google_analytics_spec.rb
> appengine/analytics: make test local

- appengine/sendgrid/Gemfile
- appengine/sendgrid/Gemfile.lock
- appengine/sendgrid/spec/sendgrid_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/sendgrid tests

- appengine/datastore/Gemfile
- appengine/datastore/Gemfile.lock
- appengine/datastore/spec/datastore_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/datastore tests

- appengine/twilio/Gemfile
- appengine/twilio/Gemfile.lock
- appengine/twilio/app.rb
- appengine/twilio/spec/twilio_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/twilio tests

- appengine/static_files/rails/Gemfile
- appengine/static_files/rails/Gemfile.lock
- appengine/static_files/rails/spec/features/static_file_serving_spec.rb
- appengine/static_files/sinatra/Gemfile
- appengine/static_files/sinatra/Gemfile.lock
- appengine/static_files/sinatra/spec/static_file_serving_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/static_files tests

- appengine/pubsub/Gemfile
- appengine/pubsub/Gemfile.lock
- appengine/pubsub/app.rb
- appengine/pubsub/spec/pubsub_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/pubsub tests

- appengine/hello_world/Gemfile
- appengine/hello_world/Gemfile.lock
- appengine/hello_world/spec/hello_world_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/hello_world tests

- appengine/memcache/spec/memcache_spec.rb
- spec/kokoro-run-all.sh
> kokoro: enable appengine/memcached tests

- .kokoro/docker/ruby-2.3/Dockerfile
- .kokoro/docker/ruby-2.4/Dockerfile
- .kokoro/docker/ruby-2.5/Dockerfile
> kokoro: update Dockerfiles

- vision/detect_pdf.rb
Project was being provided but not used, so I added it to the client initialization.
> [Vision] Add missing project argument

- vision/detect_faces.rb
- vision/draw_box_around_faces.rb
Removes unused region tags for Vision. I also deleted a section that said a delete was pending a docs update. The docs are no longer pointing to this file, so I believe it is safe to make the update now.
> [Vision] Remove unused region tags

- vision/detect_pdf.rb
- vision/draw_box_around_faces.rb
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Vision region tag update

- video/video_samples.rb
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Video Intelligence region tag update

- language/language_samples.rb
- language/quickstart.rb
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Natural Language region tag update

- speech/quickstart.rb
- speech/speech_samples.rb
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Speech region tag update

- speech/speech_samples.rb
Updates region tag per feedback
> Updates word time offsets region tag

- language/language_samples.rb
Updates region tags from _file_gcs to _gcs
> NL region tag update

- appengine/cloudsql-mysql/Gemfile
- appengine/mailgun/Gemfile
- appengine/mailgun/app.rb
- appengine/mailgun/app.yaml
- appengine/metadata_server/app.rb
Ongoing GAE region tag updates
*Docs are frozen at last commit*
> Update Region Tags

- bigquery/README.md
- bigquery/spec/bigquery_sample_spec.rb
- bigquery/tables.rb
We are no longer using this sample in the docs
> Remove unused BigQuery append sample

- storage/Gemfile
- storage/Gemfile.lock
- storage/README.md
- storage/acls.rb
- storage/buckets.rb
- storage/files.rb
- storage/iam.rb
- storage/quickstart.rb
- storage/spec/buckets_spec.rb
- storage/spec/files_spec.rb
- storage/spec/quickstart_spec.rb
> [Storage] Bucket lock samples

- iot/Gemfile
- iot/Gemfile.lock
- iot/iot.rb
- iot/spec/iot_spec.rb
Adds gateways beta samples and tests to IoT
> Cloud IoT Core Gateway beta

- datastore/sample.rb
* `datastore_transactional_single_entity_group_read_only`
> docs(samples): Update Datastore snippet for read only transaction

- pubsub/README.md
```diff
-    bundle exec ruby create_topic YOUR-PROJECT-ID new_topic
+    bundle exec ruby topics.rb create_topic YOUR-PROJECT-ID new_topic
```
> Fix missing topics.rb in README.md

- iot/spec/iot_spec.rb
Fixes nightly failure https://source.cloud.google.com/results/invocations/60b1b0a5-58de-4018-a6c3-06760ee2cd1e/targets/cloud-devrel%2Fruby%2Fruby-docs-samples%2Fsystem_tests/log
> iot - update expected error raised

- pubsub/subscriptions.rb
Fixes https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2330
> Pub/Sub: fix region tag mistake

- Gemfile
- appengine/endpoints/clients/echo_client.rb
- appengine/endpoints/clients/google_id_token_client.rb
- appengine/endpoints/clients/google_jwt_client.rb
- appengine/pubsub/app.rb
- appengine/sendgrid/app.rb
- bigtable/write_samples.rb
- endpoints/getting-started/clients/echo_client.rb
- endpoints/getting-started/clients/google_id_token_client.rb
- endpoints/getting-started/clients/google_jwt_client.rb
- firestore/get_data.rb
- firestore/paginate_data.rb
- firestore/query_data.rb
- pubsub/subscriptions.rb
- pubsub/topics.rb
- spanner/spanner_samples.rb
- stackdriver/sinatra_error_reporting.rb
- vision/product_search/product_search_add_product_to_product_set.rb
- vision/product_search/product_search_create_reference_image.rb
- vision/product_search/product_search_delete_product.rb
- vision/product_search/product_search_delete_product_set.rb
- vision/product_search/product_search_delete_reference_image.rb
Regarding some of the "=" movement: https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/466
> require google-style 1.24 and fix new lint errors

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
Example list
1. write read bool array
2. write read empty int64 array
3. write read null int64 array
4. write read int64 array
5. write read empty float64 array
6. write read null float64 array
7. write read float64 array
Ref issue: [#2579](https://github.com/googleapis/google-cloud-ruby/issues/2579)
> (spanner): write and read array of bool, int64 and float64 types examples

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
followup PR for  - modification to the `spanner_create_database` code sample
Related to - https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/485
> (spanner): write and read array of bool, int64 and float64 types examples changes

- speech/spec/speech_samples_spec.rb
change punctuation test to something more consistently transcribed
> fix speech-to-text test issue

- container-registry/container-analysis/sample.rb
- container-registry/container-analysis/spec/sample_spec.rb
replace severity with effective_severity
b/142836422
> [Container Analysis] effective severity

- .kokoro/docker/ruby-2.4/Dockerfile
- .kokoro/docker/ruby-2.5/Dockerfile
- .kokoro/docker/ruby-2.6/Dockerfile
These are blocking tests in #569 from passing.
> Added FreeTDS dependency for SQL Server to testing Dockerfiles

- README.md
- securitycenter/Gemfile
Setting as draft until blocking PRs are merged.
> Fixes badges for Ruby

- dlp/Rakefile
- dlp/acceptance/data/test.txt
A couple files that were missing from #580
> Delete some straggling files from DLP

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
- spanner/spec/spec_helper.rb
Add a code sample for creating an instance.
> spanner: add create_instance sample

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
Add the missing `spanner_delete_data` sample.
> spanner: add delete_data sample

- firestore/Gemfile.lock
- firestore/query_data.rb
- firestore/spec/query_data_spec.rb
Towards: https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/556
> firestore: in query samples, array contains filter and collection group query.

- iap/Gemfile
- iap/Gemfile.lock
- iap/iap.rb
- iap/spec/iap_spec.rb
Sample for fetching an ID Token as seen on [this documentation page](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_service_account).
Samples are dependent on https://github.com/googleapis/google-auth-library-ruby/pull/263. 
Tests will not pass on this CI until I get more info regarding testing.
Please let me know if I'm headed down the right track @dazuma !
> IAP: Samples for Requesting ID Token

- functions/test/helloworld/http_test.rb
- functions/test/helloworld/pubsub_test.rb
- functions/test/helloworld/storage_test.rb
This PR adds the following region tags:
> feat(functions): Add unit test samples

- functions/helloworld/storage_generic.rb
- functions/test/helloworld/storage_generic_test.rb
Based on:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/helloworld/index.js#L104-L124
> feat(functions): Add functions_helloworld_storage_generic

- functions/helloworld/log.rb
- functions/test/helloworld/log_test.rb
I'm not super happy with the stderr/stdout shenanigans in the tests but it seemed better than trying to mock globals.
> add helloworld_log sample

- functions/test/tips/infinite_retries_test.rb
- functions/test/tips/retry_test.rb
- functions/tips/infinite_retries.rb
- functions/tips/retry.rb
Implements the `functions_tips_retry` and `functions_tips_infinite_retries` samples.
> feat: Implement and test retry samples for Cloud Functions

- functions/firebase/firestore.rb
- functions/test/firebase/firestore_test.rb
Based on:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/firebase/main.py#L53-L69
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/firebase/main_test.py#L49-L64
> feat(functions): Add functions_firebase_firestore

- functions/concepts/filesystem.rb
- functions/concepts/requests.rb
- functions/http/content.rb
- functions/http/method.rb
- functions/test/concepts/filesystem_test.rb
- functions/test/concepts/requests_test.rb
- functions/test/http/content_test.rb
- functions/test/http/method_test.rb
adds samples and sample tests for 
functions_concepts_filesystem
functions_concepts_requests
functions_http_method
functions_http_content
> feat: add samples for http and concepts 

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
> [Spanner] database operation test - removed strict check assert

- run/events-pubsub/.dockerignore
- run/events-pubsub/.gcloudignore
- run/events-pubsub/Dockerfile
- run/events-pubsub/Gemfile
- run/events-pubsub/Gemfile.lock
- run/events-pubsub/README.md
- run/events-pubsub/app.rb
- run/events-pubsub/e2e_test_setup.yaml
- run/events-pubsub/spec/run_events_pubsub_handler_spec.rb
Adds a simple Ruby sample for Run events w/ Pub/Sub
- Uses alpha commands for consistency
> feat: add ruby run events pubsub sample

- .rubocop.yml
- functions/Rakefile
- functions/slack/Gemfile
- functions/slack/Gemfile.lock
- functions/slack/app.rb
- functions/test/slack_test.rb
> feat: Add functions slack sample

- functions/env_vars/Gemfile
- functions/env_vars/Gemfile.lock
- functions/env_vars/app.rb
- functions/test/env_vars_test.rb
> feat: Add functions_env_vars sample

- bigtable/hello_world.rb
- bigtable/read_samples.rb
fixes: https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/684
> fix mis-matched region tags

- iot/spec/iot_spec.rb
> samples: disable flaky iot test

- run/helloworld/Dockerfile
- run/helloworld/app.rb
> Update region tags for Cloud Run

- eventarc/generic/Dockerfile
- eventarc/generic/app.rb
Fixes region tags for `eventarc_generic`. Ready to merge.
> fix: update region tags for eventarc generic sample

- stackdriver/sinatra_logging.rb
> chore(logging): resolve logging_middleware sample conflict

- iap/iap.rb
- iap/spec/iap_spec.rb
Fixes https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/736, fixes https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/737, fixes https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/738
add retries to deflake
> chore(iap): deflake tests

- appengine/pubsub/app.rb
@quartzmo Per you comment: https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/719#issuecomment-768608144
Internal link for [new region tag](https://devrel.corp.google.com/snippets/gaestd_ruby_pubsub_auth_push)
> samples: correct region tag in pub/sub JWT sample

- functions/test/tips/scopes_test.rb
- functions/tips/scopes/app.rb
> Show timestamps for ruby function scope

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
Adds samples for the PITR feature.
> feat: adds the pitr samples

- .kokoro/presubmit/ruby-2.5.cfg
- .kokoro/presubmit/ruby-2.6.cfg
- .kokoro/presubmit/ruby-2.7.cfg
- .kokoro/presubmit/ruby-3.0.cfg
- .kokoro/system_tests/ruby-2.5.cfg
- .kokoro/system_tests/ruby-2.6.cfg
- .kokoro/system_tests/ruby-2.7.cfg
- .kokoro/system_tests/ruby-3.0.cfg
- Rakefile
- spec/kokoro-run-all.sh
use docker images from https://github.com/googleapis/testing-infra-docker/blob/master/ruby/multi/Dockerfile
> chore: use common docker images

- functions/firebase/remote_config/Gemfile
- functions/firebase/remote_config/Gemfile.lock
- functions/firebase/remote_config/app.rb
- functions/test/firebase/remote_config_test.rb
> feat: Implement functions_firebase_remote_config sample

- functions/firebase/rtdb/app.rb
> chore(functions): remove RTDB path params

- .github/CODEOWNERS
> chore: added codeowner file

- spanner/spanner_samples.rb
Fix insert samples. 
Fixes #804
> fix(spanner): insert statements

- spanner/spec/spanner_samples_spec.rb
> fix(spanner): list backups test

- spanner/Gemfile.lock
- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
- spanner/spec/spec_helper.rb
> feat(spanner): add samples for creating instances with processing units

- run/rails/Dockerfile
Updated the command to install Node in Dockerfile for Rails Cloud Run sample app.
> chore(run): update command for installing node in Dockerfile

- run/rails/Dockerfile
- run/rails/cloudbuild.yaml
- run/rails/config/database.yml
- run/rails/config/environments/production.rb
- run/rails/config/storage.yml
Add region tags to files in Rails Cloud Run sample app to use as snippets in documentation
> chore(run): add region tags to rails cloud run sample app

- run/rails/Dockerfile
- run/rails/Gemfile
- run/rails/app/views/photos/index.html.erb
Edit Dockerfile to update bundler, remove Ruby version from the Gemfile to remove the parsing issue/warning from rvm, and ensure that the version of ruby required is delegated to one place: the Dockerfile, edit the empty album description in index.html.erb to be in the middle of the page and consistent with the "New Photo" button.
> chore(run): edit Dockerfile, Gemfile, and index.html.erb

- run/rails/cloudbuild.yaml
> fix: run/rails/cloudbuild.yaml step 2 args typo

- spanner/Gemfile.lock
- spanner/json_column_type_samples.rb
- spanner/spec/json_column_type_spec.rb
- spanner/spec/spec_helper.rb
> feat(spanner): JSON column type samples

- spanner/spanner_samples.rb
- spanner/spec/spanner_samples_spec.rb
Support for copy backup feature.
> feat(spanner): add support for copy backup feature

- functions/helloworld/storage/app.rb
> chore(functions/storage): clarify comments

- functions/Gemfile
- functions/Gemfile.lock
> chore: Ensure minitest-junit is part of the functions test bundle

- functions/helloworld/pubsub/app.rb
- functions/helloworld/storage/app.rb
> fix(functions): add 2nd-gen region tag

- run/helloworld/Gemfile
- run/helloworld/Gemfile.lock
- run/helloworld/spec/e2e_spec.rb
> fix(run): add retries + log 500 errors

- appengine/standard-storage/Gemfile
- appengine/standard-storage/Gemfile.lock
> chore: test failure fix for appengine standard storage

- getting-started/bookshelf/Dockerfile
> Add Dockerfile for BookShelf app

- spanner/spanner_samples.rb
> sample(spanner): show support for data_boost_enabled

- run/helloworld/Gemfile
- run/helloworld/Gemfile.lock
> fix: update dependencies, add Gemfile.lock

- renovate.json
Disable renovate bot since we're now going to use dependabot
> chore(deps): disable renovate bot

- .github/CODEOWNERS
- .github/blunderbuss.yml
Update sample repo code owners to infra-db-sdk
> chore: update code owners to infra-db-sdk

- stackdriver/sinatra_error_reporting.rb
align code sample for error reporting with code in other languages (b/275730159):
- use the "fixed" error message
> fix: refactor error reporting code sample

- spec/e2e.rb
> chore: make the randomizer more random

- spanner/spec/spanner_alter_table_with_foreign_key_delete_cascade_spec.rb
- spanner/spec/spanner_create_table_with_foreign_key_delete_cascade_spec.rb
- spanner/spec/spanner_drop_foreign_key_constraint_delete_cascade_spec.rb
- spanner/spec/spanner_sequence_spec.rb
Fixes #1462
Fixes #1463
Fixes #1464
Fixes #1465
Fixes #1466
Fixes #1467
Fixes #1468
> tests: Fixed syntax of some expectations

- functions/test/slack_test.rb
Fixes #1480 
Fixes #1481 
Fixes #1482
> tests(functions): Fix a test flake by ensuring ostruct is available

- functions/helloworld/get/Gemfile
We need this sample to display without the comments in docs.
> Update Gemfile with region tags

- functions/README.md
> Update README.md to reflect Cloud Run functions rebrand

- appengine/endpoints/app.rb
- appengine/endpoints/clients/echo_client.rb
- appengine/endpoints/clients/google_id_token_client.rb
- appengine/endpoints/clients/google_jwt_client.rb
- appengine/flexible/ruby31-and-earlier/endpoints/app.rb
- appengine/flexible/ruby31-and-earlier/endpoints/clients/echo_client.rb
- appengine/flexible/ruby31-and-earlier/endpoints/clients/google_id_token_client.rb
- appengine/flexible/ruby31-and-earlier/endpoints/clients/google_jwt_client.rb
- endpoints/getting-started/app.rb
- endpoints/getting-started/clients/echo_client.rb
- endpoints/getting-started/clients/google_id_token_client.rb
- endpoints/getting-started/clients/google_jwt_client.rb
- endpoints/getting-started/deployment.yaml
- getting-started/authenticating-users/app.rb
- getting-started/authenticating-users/app.yaml
- getting-started/gce/deploy.sh
- getting-started/gce/startup-script.sh
- getting-started/gce/teardown.sh
> chore(oss): correct apache license headers

- appengine/analytics/app.rb
- appengine/cloud-tasks/app.rb
- appengine/datastore/app.rb
- appengine/hello_world/app.rb
- appengine/metadata_server/Gemfile
- appengine/metadata_server/Gemfile.lock
- appengine/metadata_server/app.rb
- appengine/metadata_server/app.yaml
- appengine/pubsub/app.rb
- appengine/standard-analytics/app.yaml
- appengine/standard-cloud-tasks/app.yaml
- appengine/standard-datastore/app.yaml
- appengine/standard-hello_configs/app.yaml
- appengine/standard-hello_world/app.yaml
- appengine/standard-metadata-server/app.rb
- appengine/standard-metadata-server/app.yaml
- appengine/standard-storage/app.yaml
- appengine/storage/app.rb
- appengine/storage/spec/storage_spec.rb
- appengine/twilio/app.rb
- appengine/websockets/app.rb
- appengine/websockets/spec/websockets_spec.rb
Continuation of #1526
* Ensure host authorization for all hosts while in development (solves for "Host not permitted")
> fix: update appengine samples to allow local dev testing

- cdn/Gemfile
- endpoints/getting-started/spec/endpoint_sample_spec.rb
- functions/test/firebase/firestore_test.rb
- functions/test/firebase/rtdb_test.rb
- media_cdn/Gemfile
Fixes #1558 
Fixes #1559 
Fixes #1560 
Fixes #1534
> tests: Various fixes to tests

- appengine/flexible/hello_world/Gemfile
Update flex quickstart sample tagging
> Update flex quickstart sample tagging

- CONTRIBUTING.md
- appengine/flexible/pubsub/Gemfile
- appengine/flexible/pubsub/app.rb
- appengine/flexible/pubsub/spec/pubsub_spec.rb
- appengine/flexible/ruby31-and-earlier/pubsub/Gemfile
- appengine/flexible/ruby31-and-earlier/pubsub/app.rb
- appengine/flexible/ruby31-and-earlier/pubsub/spec/pubsub_spec.rb
- appengine/pubsub/Gemfile
- appengine/pubsub/app.rb
- appengine/pubsub/spec/pubsub_spec.rb
Follows https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-pubsub/OVERVIEW.md
> chore: Update appengine samples to google-cloud-pubsub/v3.x
